# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Breathe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Breathe

  pod "MBCircularProgressBar"


  target 'BreatheTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BreatheUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
